name: gemel
description: Types and logic shared by gemel_app and gemel_www.
version: 1.0.0
# homepage: https://www.example.com
repository: https://github.com/david-fong/gemel/tree/main/packages/gemel
environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
