include: package:lints/recommended.yaml
# http://dart-lang.github.io/linter/lints.
# https://dart.dev/guides/language/analysis-options

# Uncomment to specify additional rules.
# linter:
#   rules:

# analyzer:
#   exclude:
#     - path/to/excluded/files/**
