name: gemel_www
description: Server for a development ecosystem aiming for structure and human-friendliness.
version: 1.0.0
# homepage: https://www.example.com
repository: https://github.com/david-fong/gemel/tree/main/packages/gemel_www

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0

dev_dependencies:
  lints: ^1.0.1
