[package]
workspace = "../.."
name = "gemel-lib"
version = "0.1.0"
description = "Shared code for gemel apps."
categories = ["text-editors"]
license = "MIT"
edition = "2018"

[dependencies]
serde_json = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
