[package]
publish = false
workspace = "../../.."
name = "gemel-website"
version = "0.1.0"
license = "MIT"
edition = "2018"

[dependencies]
serde_json = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
